CREATE TABLE EMP (
    EMP_ID VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(64),
    FIRST_NAME VARCHAR(64),
    EMAIL VARCHAR(128),
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID)
);

CREATE TABLE SHIFT(
	SHIFT_ID INTEGER NOT NULL, 
	SHIFT_START_TIME char(4) NOT NULL, 
	SHIFT_END_TIME char(4) NOT NULL,
	CONSTRAINT SHIFT_PK PRIMARY KEY (SHIFT_ID)
);

CREATE TABLE EMP_SHIFT(
	EMP_ID VARCHAR(32) NOT NULL,
	SHIFT_ID INTEGER NOT NULL, 
	CLOCK_IN_TIME CHAR(4),
	CLOCK_OUT_TIME CHAR(4),
	WORKING_DATE DATE NOT NULL,
	CONSTRAINT EMP_SHIFT_PK PRIMARY KEY (EMP_ID, SHIFT_ID,WORKING_DATE),
	CONSTRAINT EMP_SHIFT_FK1 FOREIGN KEY (EMP_ID) REFERENCES EMP(EMP_ID),
	CONSTRAINT EMP_SHIFT_FK2 FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT(SHIFT_ID)
);
insert into shift values (1, '0600', '1400');
insert into shift values (2, '1400', '2200');
insert into shift values (3, '2200', '0600');

commit;
